### ISSUE TITLE
Is there any plan of "custom CSS selector/property/value" spec for webcomponents?

### ISSUE THREAD

**Issue by Jinjiang** [WICG/webcomponents#40]
As the title, something simply thought same as custom elements but focus on CSS.
for example, people can encapsulate and more easily use the element styles just like:

``` css
apple-watch::case {
  material: steel;
}
```

Thx
